### ISSUE TITLE
calculate SDR on individual wavs files

### ISSUE THREAD

**Issue by Edresson** [JusperLee/Calculate-SNR-SDR#1]
Hi, Thanks for this implementation :),

I would like to know how I can calculate the SDR of 2 individual wave files!

I have the model output, the expected wav file and the model input file (the audio with the two voices mixed). The audio is single channel!

How can I get the SDR value for this sample?

**Comment by JusperLee** [comment]
You can use librosa to read audio, and then directly input to SNR.py or SDR.py.
